export const LOGIN = {
  SUCCESS: 'LOGIN.SUCCESS',
  FAIL: 'LOGIN.FAIL',
};

export const NEWS_EDIT = {
  SUCCESS: 'NEWS_EDIT.SUCCESS',
  FAIL: 'NEWS_EDIT.FAIL',
};

export const NEWS_CREATE = {
  SUCCESS: 'NEWS_CREATE.SUCCESS',
  FAIL: 'NEWS_CREATE.FAIL',
};

export const NAVIGATE = {
  CHANGE_ADMIN: 'NAVIGATE.CHANGE_ADMIN',
};

export const NEWS_LIST = {
  GET_SUCCESS: 'NEWS_LIST.GET_SUCCESS',
  GET_START: 'NEWS_LIST.GET_START',
  GET_ERROR: 'NEWS_LIST.GET_ERROR',
};

export const NEWS_VIEW = {
  GET_SUCCESS: 'NEWS_VIEW.GET_SUCCESS',
  GET_START: 'NEWS_VIEW.GET_START',
  GET_ERROR: 'NEWS_VIEW.GET_ERROR',
};
